vuejs/vuefire

package.json
I just noticed the link was wrong on the right-hand side of [the npm page](https://www.npmjs.com/package/vuefire).
=> Fixed GitHub URL links in package.json

README.md, package.json, src/vuefire.js, tests/vuefire.spec.js
I would like to refer to the change about .key/.value. I believe that the `item._key` it is more clean and readable than the `item['.key']`.
For details about the other changes, you could check the updated readme.
Let me know if you agree with that changes, to continue with tests.
=> Upgraded to the Firebase 3.x.x SDK

src/vuefire.js, tests/vuefire.spec.js
This should fix #19 and close #20 
Conditionally defining the property as reactive should be a better choice than deleting the binding
I'm wondering if we should automatically unbind when binding if a binding already exist. It'll prevent the user from calling unbind each time he wants to bind a new ref
=> Fix array rebind

examples/todo-app/index.html
=> add item updates to the todo-app example

README.md
With an short example to remind of using 'null' as a third argument if only readyCallback is wanted.
=> Mentioned callback functions for manual binding

src/utils.js, test/utils.spec.js
Firestore has native support for timestamps, which show up in JS as `Date` objects. We need a special case in `extractRefs` because recursing into a `Date` and copying its fields doesn't produce a proper copy. Instead we should pass it through the same way we do with more fundamental types, like strings or numbers.
=> Pass through Date objects unscathed

examples/todo-app/index.html, package-lock.json, package.json, src/vuefire.js, tests/vuefire.spec.js
From #121 
This PR is not meant to be merged yet; it's more to start a discussion on a possible breaking change.
The idea is to make .key non-enumerable.
Sometimes we use JS Objects as maps in firebase.
When we loop on a bound reference, .key gets in the way and we need to manually ignore it with a condition. Making the .key property non-enumerable fixes this.
(For consistency .value is also configured as non-enumerable.)
IMHO it makes vuefire easier to use but it may break existing code. I don't know anything about the potential performance implications. At your request I can make it an option instead.
If this idea garners interest I will modify the failing tests and write new ones. Perhaps could we also talk about writable and configurable.
cc @yacinehmito
=> feat: make value and key non enumerable

package.json, src/index.js, test/helpers/mock.js
The Firebase JS SDK introduced some breaking changes in 5.0.0:
https://github.com/firebase/firebase-js-sdk/commit/0997040b6a231e54cbc2d6f8c293a78e83451220
Fixes #183.
=> index.js: docChanges is now a method

packages/vuexfire/package.json
Hi! I attempted to update from `vuexfire@3.0.0-alpha.5` to `alpha.8` and began receiving this error in my project:
```
This dependency was not found:
* vuexfire in ./src/store/index.ts, ./src/store/login/actions.ts
```
It appears starting with `alpha.6`, the files in the `dist/` folder were named differently (ex: `vuexfire.cjs.js` became `vuexfire.common.js`), which breaks tools like Webpack and TypeScript.
This updates the entry points to reflect the files as they're published in NPM.
=> fix(vuexfire): Correct main/module/browser entries

packages/vuexfire/types/index.d.ts, packages/vuexfire/types/test/index.ts
To fix type errors for binding a collection with `where`, `order`, `limit`, and so on.
`firestore.CollectionReference` extends `firestore.Query` and `firestore.Query` is more appropriate as `bindFirebaseRef` is not dependent on the interface extended by `firestore.CollectionReference`.
=> [VuexFire] Use firestore.Query instead of firestore.CollectionReference

packages/vuexfire/src/index.js
Hey! I was having trouble with getting nested references populated on documents in a collection using `vuexfire`. It works completely fine on the initial binding, but any changes to the document seems to discard any other unmodified references.
Here's an example:
```js
Article {
title: 'Cool story',
author: { // Reference to a user document
id: 'someUserId',
name: 'Renowned writer'
},
body: 'Good words',
comments: [ // List of references to comment documents
{
id: 'someCommentId',
text: 'Wow that was good stuff'
},
{
id: 'someOtherCommentId',
text: 'Moved me to tears tbqh'
}
]
}
```
If I update that document by with a new comment, any existing references are lost but the new one is populated. The end result looks something like this:
```js
Article {
title: 'Cool story',
author: …
```
=> Fix loss of nested references on documents when binding a collection in Vuexfire

packages/@posva/vuefire-core/jest.config.js, packages/@posva/vuefire-core/package.json, packages/@posva/vuefire-core/src/index.js, packages/@posva/vuefire-core/src/rtdb.js, packages/@posva/vuefire-core/test/collection.spec.js, packages/@posva/vuefire-core/test/document.spec.js, packages/@posva/vuefire-core/test/rtdb/as-array.spec.js, packages/@posva/vuefire-core/test/rtdb/as-object.spec.js, packages/@posva/vuefire-test-helpers/src/index.js, packages/documentation/docs/api/vuefire.md, packages/documentation/docs/api/vuexfire.md, packages/documentation/docs/vuefire/binding-subscriptions.md, packages/documentation/docs/vuexfire/binding-subscriptions.md, packages/vuefire/jest.config.js, packages/vuefire/package.json, packages/vuefire/src/index.js, packages/vuefire/src/rtdb.js, packages/vuefire/test/rtdb/bind.spec.js, packages/vuefire/types/test/index.ts, packages/vuefire/types/vue.d.ts, packages/vuexfire/jest.config.js, packages/vuexfire/package.json, packages/vuexfire/src/index.js, packages/vuexfire/src/rtdb/index.js, packages/vuexfire/test/index.spec.js, packages/vuexfire/test/rtdb/index.spec.js, packages/vuexfire/types/index.d.ts, packages/vuexfire/types/test/index.ts
Closes #264 
BREAKING CHANGE: the default behavior is now resetting the data when unbinding. To keep the data as is, you have to provide a `reset: false` option
=> feat: add reset option

packages/@posva/vuefire-core/src/utils.js, packages/@posva/vuefire-core/test/refs-documents.spec.js
Fixes #283 
I'm still confused about how this works, but it does pass the test.
Basically, when updating an array I discard all the old values that are no longer in the new document and pass it as the "oldDoc" to the recursive `extractRefs`.
It passed all the tests, but I don't know if it breaks anything untested, which is pretty hard to predict.
I also changed the `extractRefs` function to use `for in` instead of `reduce` and added 2 new variables
for the result indexes instead of accessing them manually every time
=> Old array elements are removed from binding

packages/documentation/docs/vuexfire/querying.md
This firestore action made use of   db.ref('documents').orderByChild('createdAt') instead of db.collection('blogs').orderBy('created_at', 'desc') according to firestore documentation.
=> Update Firestore ordering method to use orderBy()

packages/documentation/docs/vuefire/querying.md
QuerySnapshot class doesn't have map function. docs property is always an array and works with map regardless if Firestore Query yields results or not.
=> Example for One Time Read didn't work anymore

packages/@posva/vuefire-core/__tests__/firestore/collection.spec.ts, packages/@posva/vuefire-core/__tests__/firestore/document.spec.ts, packages/@posva/vuefire-core/__tests__/firestore/options.spec.ts, packages/@posva/vuefire-core/__tests__/firestore/refs-collections.spec.ts, packages/@posva/vuefire-core/__tests__/firestore/refs-documents.spec.ts, packages/@posva/vuefire-core/__tests__/rtdb/as-array.spec.ts, packages/@posva/vuefire-core/__tests__/rtdb/as-object.spec.ts, packages/@posva/vuefire-core/__tests__/rtdb/options.spec.ts, packages/@posva/vuefire-core/__tests__/shared.spec.ts, packages/@posva/vuefire-test-helpers/src/index.ts, packages/vuefire/src/index.ts
I noticed that every time `createOps` is called, `walkSet` is imported in all spec files that use it.
This PR adds the default walkset as the default parameter, so there's no need to pass it every time `createOps` is called
=> Removed unnecessary walkset imports when creating ops - Unit Tests Refactoring

packages/documentation/docs/api/vuefire.md, packages/documentation/docs/api/vuexfire.md, packages/documentation/docs/vuefire/README.md, packages/documentation/docs/vuefire/getting-started.md, packages/documentation/docs/vuexfire/README.md, packages/documentation/docs/vuexfire/getting-started.md
While going through the tutorial I was confused where `firebase` came from so I thought it would be helpful to add it to the examples. some of the other docs have imports so I thought these should also have them.
=> added firebase imports to docs

packages/documentation/docs/vuefire/binding-subscriptions.md
to make it easier for beginners
=> Clarified role of the two binding methods

packages/documentation/docs/api/vuefire.md
In this example :  
https://vuefire.vuejs.org/api/vuefire.html#options-serialize
```js
const serialize = (snapshot: firestore.DocumentSnapshot) => {
// documentSnapshot.data() DOES NOT contain the `id` of the document. By
// default, Vuefire adds it as a non enumerable property named id.
// This allows to easily create copies when updating documents, as using
// the spread operator won't copy it
return Object.defineProperty(doc.data(), 'id', { value: doc.id })
}
```
`doc` isn't defined, i think it should be `snapshot` instead of.
=> docs: changes doc by snapshot in serialize example

package.json
NPM 7 attempts to automatically resolve peer dependencies and errors if it can't. This makes it difficult to use this package with Vue 3, since `@vue/composition-API` depends on Vue 2. This change brings `vuefire` in line with the README from `vue-demi`.
Pending this change, a workaround is to use `--legacy-peer-deps` when installing.
=> fix: make @vue/composition-api optional

packages/documentation/docs/vuexfire/writing-data.md
changing "this.user.id" to "state.user.id" in firestore example for "Updates to collection and documents"
=> docs: fix example for "Updates to collection and documents"

docs/cookbook/migration-v2-v3.md
Fix a wrong module call on the document, it was being called VueFireFirestoreOptionsAPI (instead of VueFireDatabaseOptionsAPI) in the database apart.
=> docs: deprecations correction in migration

docs/guide/auth.md, src/auth/index.ts, src/auth/user.ts, src/index.ts
Closes https://github.com/vuejs/vuefire/issues/1306
=> feat(auth): `useIsCurrentUserLoaded()` composable

docs/guide/firebase-composables.md
While working on #1382, I noticed this empty code block in the docs. This PR removes it.
=> docs: remove redundant code block from docs

packages/nuxt/src/runtime/admin/plugin.server.ts, packages/nuxt/src/runtime/analytics/plugin.client.ts, packages/nuxt/src/runtime/app-check/plugin.client.ts, packages/nuxt/src/runtime/app-check/plugin.server.ts, packages/nuxt/src/runtime/app/composables.ts, packages/nuxt/src/runtime/app/plugin.client.ts, packages/nuxt/src/runtime/app/plugin.server.ts, packages/nuxt/src/runtime/auth/plugin-mint-cookie.client.ts, packages/nuxt/src/runtime/auth/plugin-user-token.server.ts, packages/nuxt/src/runtime/auth/plugin.client.ts, packages/nuxt/src/runtime/auth/plugin.server.ts, packages/nuxt/src/runtime/emulators/auth.plugin.ts, packages/nuxt/src/runtime/emulators/database.plugin.ts, packages/nuxt/src/runtime/emulators/firestore.plugin.ts, packages/nuxt/src/runtime/emulators/functions.plugin.ts, packages/nuxt/src/runtime/emulators/storage.plugin.ts, packages/nuxt/src/runtime/payload-plugin.ts, packages/nuxt/templates/plugin.ejs
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
=> fix: import nuxt composables from #imports

packages/nuxt/src/module.ts
https://github.com/nuxt/nuxt/issues/24733 is caused by Nuxt not treating `.ejs` files as JavaScript (and therefore not running certain build plugins on the code within them).
We might be able to handle this transparently within Nuxt as well but this PR fixes it in a backwards-compatible way.
=> fix(nuxt): give plugins `.mjs` extension so they're processed

docs/guide/realtime-data.md
This pull requests fixes the example order for using null data sources with in the [Realtime Data Guide](https://vuefire.vuejs.org/guide/realtime-data.html#Declarative-realtime-data).
This will then show the correct example for either Firestore or Realtime Database.
=> docs: fix ordering on null data source examples

docs/nuxt/auth.md
Hi, I had some trouble with this example once I added the '.global' suffix to the file (the whole application requires credentials) where I was (I assume at least) getting an infinite redirection recursion to the /login route. Since this is a fairly common use for auth middlewares, I think making it more clear (either through code, a comment or a markdown tip) that applying it to '/login' causes that would avoid others falling into this little pitfall.
=> avoid infinite redirection

src/database/useDatabaseRef.ts, src/firestore/useFirestoreRef.ts, src/storage/index.ts, tests/database/list.spec.ts, tests/firestore/collection.spec.ts
Closes #1495
Checking if the `docOrCollectionRef` is a ref before setting up a watch to re-bind the firestore meant getters weren't being watched. 
Using `watch(() => toValue(docOrCollectionRef), bindFirestoreRef)` will keep the old behaviour of tracking refs and computeds while also tracking getters.
In this case, we also don't need to check what `docOrCollectionRef` is.
Unless there is a cost in watching an non-reactive source (I don't think so, but I'm not sure).
I'm still learning my way around the tests, I tried the following, but the tests hangs and fails:
```ts
it('can be bound to a getter', async () => {
const listCollectionRef = collection<{ name: string }>()
const listRef = ref<null | CollectionReference>(null)
const { wrapper } = factory({
ref: () => listRef.value,
})
await …
```
=> fix: bindFirestoreRef not reacting to getter

packages/nuxt/package.json, packages/nuxt/src/module.ts, pnpm-lock.yaml
We are going to be removing support for [compiling templates from disk using `lodash.template`](https://github.com/nuxt/nuxt/issues/25332) in Nuxt v4. This is a PR to move lodash usage directly into vuefire's Nuxt module.
It would also be possible to avoid using it entirely, which I would _strongly_ recommend, either:
* using a custom function to handle the replacement, such as in https://github.com/nuxt-modules/color-mode/pull/240
* or moving the string interpolation logic directly into `getContents`
=> fix(nuxt): use `lodash.template` directly to compile templates

docs/nuxt/environment-variables.md
I know it's longer than 1 sentence, but I think an example would be beneficial.
On a related note, I wonder if having the lack of vuefire config a warning instead of an error would be a better dx. This is how the Sanity module does it (and doesn't prevent Nuxt from starting altogether):
vs Vuefire:
=> docs: add Nuxt note about public environment variables

packages/nuxt/src/module.ts, src/database/optionsApi.ts, src/firestore/optionsApi.ts
In line with https://github.com/vuejs/router/pull/2295 and https://github.com/nuxt/nuxt/pull/28542, this moves to augment `vue` rather than `@vue/runtime` core.
This is now officially recommended [in the docs](https://vuejs.org/api/utility-types.html#componentcustomproperties) and it _must_ be done by all libraries or it will break types for _other_ libraries.
=> fix: augment `vue` rather than `@vue/runtime-core`

docs/guide/getting-started.md
When following [the documentation to try and implement Firebase](https://vuefire.vuejs.org/guide/getting-started.html)  for a Nuxt project I stumbled upon a typo where the import for a database reference was a written as `import { getDatabase, dbRef } from 'firebase/database'` as opposed to `import { getDatabase, ref as dbRef } from 'firebase/database'` as the rest of the document.
=> Typo on "Getting started" doc

.github/workflows/docs-prs.yml, .github/workflows/docs.yml, package.json, packages/nuxt/playground/firebase.json, playground/functions/package.json
Firebase 12.0.0 has just been released. 
https://github.com/firebase/firebase-js-sdk/releases/tag/firebase%4012.0.0
I think the only notable change for this project is the new [minimum Node version of 20](https://github.com/firebase/firebase-js-sdk/pull/9128).
=> feat: support Firebase 12

packages/nuxt/package.json
A follow up of https://github.com/vuejs/vuefire/pull/1629, I forgot to add it to the Nuxt module.
=> feat(nuxt): allow Firebase 12
