vuejs/vuefire

package.json

Fixes #2. Version 1.0.1 here we come :)

Updated package.json's "main" key to point to correct dist file

---

tests/vuefire.spec.js

the test label was the same as the previous one. By what the test does this looks like a fine label to me

Fix test label

---

README.md

Adds a complete example showing how to save user input to Firebase.

Adds a complete example

---

README.md

@posva I think you will be able to edit this one. I had to close the previous one #42  and create a new one to allow edits from maintainers.

Adding deletion and update info

---

README.md
examples/todo-app/index.html

firebase-js-sdk has been updated.
https://github.com/firebase/firebase-js-sdk/releases/tag/v4.2.0
I check test codes and example todo app

Update firebase 4.0.0 to 4.2.0

---

types/vue.d.ts

Fixes: https://github.com/vuejs/vuefire/issues/209

added missing firestore.Query type declarationg

---

packages/vuefire/README.md

Fix a typo in the package README.

Fix a typo

---

packages/vuexfire/package.json
packages/vuexfire/types/index.d.ts
packages/vuexfire/types/test/index.ts
packages/vuexfire/types/test/tsconfig.json
packages/vuexfire/types/tsconfig.json

Reference issue: https://github.com/vuejs/vuefire/issues/224

Add types of VuexFire

---

packages/vuexfire/types/index.d.ts
packages/vuexfire/types/test/index.ts

Hi there
Stumbled upon this missing argument in the type definition file.
Cheers!

Update typings to include the maxRefDepth option

---

packages/documentation/docs/vuexfire/writing-data.md

Fixing typo with updating Firestore documents

---

packages/documentation/docs/vuefire/writing-data.md

docs: fix method

---

packages/documentation/docs/vuexfire/querying.md

This is changed now for Vuexfire too.

Same thing as before with One Time Read example

---

packages/documentation/docs/vuexfire/binding-subscriptions.md

Some missing end brackets and commas.

docs(vuexfire): fix binding-subscriptions example

---

packages/documentation/docs/vuexfire/binding-subscriptions.md

Not a native speaker but this sounds kinda right to me

docs: typo

---

packages/vuexfire/README.md

this is _really_ minor, and yes, we should not just copy-pasta our way through life, but i made the same error as in #242, in part from the example.

docs: make example consistent (#925) [skip ci]

---

docs/guide/getting-started.md

docs: fix typo between firestore and database

---

docs/guide/ssr.md

docs: fix typo in ssr docs

---

README.md

Update README.md (#1262) [skip ci]

---

docs/cookbook/migration-v2-v3.md

docs: Update migration-v2-v3.md

---

docs/index.md

You`'ll` still be able to use `the` Firebase JS SDK to its full potential!
or 
You `will` still be able to use `the` Firebase JS SDK to its full potential!

docs: adjust verb tense in performant blurb

---

docs/guide/auth.md

Align docs to have similar code with nuxt
https://vuefire.vuejs.org/nuxt/auth.html#authentication

docs(auth): rename redirectTo to redirect

---

docs/.vitepress/theme/components/VueMasteryBanner.vue

Update Vuemastery pinia discount banner.
Desktop
Mobile

Update vuemastery banner

---

src/auth/user.ts

fix: use value of currentUser ref in useIsCurrentUserLoaded

---

src/shared.ts

See https://github.com/vuejs/vuefire/discussions/1321

chore: remove experimental flag

---

docs/guide/options-api-realtime-data.md

Make it easier to follow the various ways available to achieve this.

Doc: Enhance comments for `reset` option

---

firebase.json
packages/nuxt/package.json
packages/nuxt/playground/database.rules.json
packages/nuxt/playground/firebase.json
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/playground/package.json
packages/nuxt/playground/storage.rules
packages/nuxt/src/module.ts
packages/nuxt/src/module/emulators.ts
packages/nuxt/src/module/options.ts
packages/nuxt/src/runtime/app/lru-cache.ts
packages/nuxt/src/runtime/app/plugin.server.ts
packages/nuxt/src/runtime/auth/api.session-verification.ts
packages/nuxt/src/runtime/auth/plugin.server.ts
packages/nuxt/src/runtime/emulators/auth.plugin.ts
packages/nuxt/src/runtime/emulators/database.plugin.ts
packages/nuxt/src/runtime/emulators/firestore.plugin.ts
packages/nuxt/src/runtime/emulators/functions.plugin.ts
packages/nuxt/src/runtime/emulators/storage.plugin.ts
packages/nuxt/templates/plugin.ejs
pnpm-lock.yaml
src/server/app-check.ts
src/server/auth.ts

feat: add emulators support

---

docs/guide/auth.md

This could also be: ~When~ if a user

Adjust grammar 

---

docs/nuxt/getting-started.md

fix for 
The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.

docs: mention .env

---

src/index.ts

fix: export databaseDefaultSerializer (#1481)
